### ISSUE TITLE
Revel question

### ISSUE THREAD

**Issue by error56** [tyler-sommer/stick#21]
Hi, is stick support Revel templates? Can I adapt stick into Revel without risk? Thanks

**Comment by tyler-sommer** [comment]
Hi @error56 , thanks for opening this!

Looking at the Revel docs on using a custom template engine (here: https://revel.github.io/manual/template-engine.html), it seems reasonable enough and stick should have no problem, excepting some adapter code to make stick implement the proper interfaces. 

I don't use Revel myself, so the adapter code is up to you :) Let me know how it goes!
