### ISSUE TITLE
If key of ctx has prefix "and" or "or" for function Execute, it errors

### ISSUE THREAD

**Issue by mingwho** [tyler-sommer/stick#23]
```package main

import (
	"log"
	"os"
    
	"github.com/tyler-sommer/stick"
)

func main() {
	env := stick.New(nil)
	if err := env.Execute("Hello, {{ order }}!", os.Stdout, map[string]stick.Value{"order": "ABCD"}); err != nil {
		log.Fatal(err)
	}
}
```

Something like this causes error `parse: unexpected token "OPERATOR" on line 1, column 10`

**Comment by azaleas** [comment]
I think this is due to this line https://github.com/tyler-sommer/stick/blob/05634229ddd17c5a0244788fbdb9995729bb42b0/parse/operator.go#L18

The regex here just checks the start of the string and matches the entire string. To match the keyword exactly you can try using:

```go
	operatorMatcher = regexp.MustCompile(`^(not in|not|\*\*|is not|//|>=|<=|` + strings.Join(ops, "|") + ")$")
```

With `$` sign at the end the match should be exact.

**Comment by mingwho** [comment]
> I think this is due to this line
> 
> https://github.com/tyler-sommer/stick/blob/05634229ddd17c5a0244788fbdb9995729bb42b0/parse/operator.go#L18
> 
> The regex here just checks the start of the string and matches the entire string. To match the keyword exactly you can try using:
> 
> ```go
> 	operatorMatcher = regexp.MustCompile(`^(not in|not|\*\*|is not|//|>=|<=|` + strings.Join(ops, "|") + ")$")
> ```
> 
> With `$` sign at the end the match should be exact.

I tried adding the `$` sign at the end of the regex expression, it causes some other tests to fail. As an alternative solution, I'm updating the lexer so it checks for extra space after operator if we match the string and if operator is alphabetic (this is because we still want something like {{ 1*2 }} to work). Pls check this PR https://github.com/tyler-sommer/stick/pull/24

**Comment by mingwho** [comment]
Resolved
