### ISSUE TITLE
Include "with" syntax to pipe in variables doesn't work

### ISSUE THREAD

**Issue by davelondon** [tyler-sommer/stick#5]
The "with" syntax [detailed here](http://twig.sensiolabs.org/doc/tags/include.html) that is used to inject variables into an included template doesn't seem to work:

```
// fragment.twig
{{ foo }}
```

```
// main.twig
{% include "fragment.twig" with {"foo": "bar"} %}
```

The error is:

```
parse: unexpected token "HASH_OPEN" on line 1, column 31
```

**Comment by davelondon** [comment]
However, this works:

```
// main.twig
{% set vars = {"foo": "bar"} %}
{% include "fragment.twig" with vars %}
```

**Comment by tyler-sommer** [comment]
Thanks! It looks like parsing the include tags doesn't allow for map literals, that will definitely have to change.

**Comment by tyler-sommer** [comment]
I'm happy to say that this is now implemented so I'll close this issue. Please open another issue if you run into any problems. Thanks!
