### ISSUE TITLE
New tag version

### ISSUE THREAD

**Issue by fsmiamoto** [tyler-sommer/stick#51]
We've been using it in production and since had the issue described in #44
Although we can build our project using the current HEAD, I would suggest creating a new `v1.0.4` tag for it since it would include
this important fix.

Thanks for the awesome job!

**Comment by tyler-sommer** [comment]
Good call-- I've tagged [v1.0.4 to the latest master](https://github.com/tyler-sommer/stick/releases/tag/v1.0.4) so I'll close this. Thanks for the suggestion, @fsmiamoto!
