### ISSUE TITLE
Panic when parsing

### ISSUE THREAD

**Issue by davelondon** [tyler-sommer/stick#7]
I see a panic while parsing this:

```
{{ foo.bar() }}
```

```
panic: reflect: call of reflect.Value.Type on zero Value
```

... better would be an error.

**Comment by tyler-sommer** [comment]
Indeed, proper checks need to be performed in the value API, which I haven't gotten around to as yet.

Thanks for the report!

**Comment by tyler-sommer** [comment]
Hi @davelondon, this specific panic has been fixed. I opened up #11 as a general issue about error handling. I'm going to close this, but as always, please open an issue if you run into any problems! Thanks for your feedback 👍
