### ISSUE TITLE
Arrays don't work

### ISSUE THREAD

**Issue by davelondon** [tyler-sommer/stick#9]
The following...

```
{% set foo = ["bar", "baz"] %}
```

... gives an error:

```
parse: unexpected token "ARRAY_OPEN"
```

**Comment by davelondon** [comment]
... additionally:

```
{% set foo = {"bar": "baz"} %}
```

... gives an error:

```
parse: unexpected token "HASH_OPEN"
```

**Comment by tyler-sommer** [comment]
Thanks for the report, @davelondon. I've started implementing hash and array literals in 0eaebd4 but `{% include with {"hash": "literal"} %}` still doesn't work and stick doesnt yet support `{key: "value"}` syntax with the unquoted key name.

**Comment by tyler-sommer** [comment]
This is now implemented completely. Please let me know if you have any issues, and thanks again @davelondon! 👍
